const laptops = [
  {
    name: "Acer Aspire 3 A311-45 (UN.354SI.002) ",
    price: 28600 ,
    ram: 8 ,
    battery: 2,
    brand: "Acer",
    status: "Available",
    processor: "Intel Celeron Dual-Core - N4500",
    screen: 11.6 ,
    storage: 512,
    graphics: "Intel UHD",
    os: "Windows 11 Home Basic",
    rating: 3,
    fingerprint: false,
    touch: false,
    color: "Steel Grey",
    faceUnlock: true,
    image: "./images/Acer-1.avif"
  },
  {
    name: "Acer Aspire 3 A325-42 (UN.34QSI.002)",
    price: 40990,
    ram: 16,
    battery: 3,
    brand: "Acer",
    status: "Available",
    processor: "Ryzen",
    screen: 15.8,
    storage: 512,
    graphics: "AMD Radeon",
    os: "Windows 11 Home Basic",
    rating: 4.1,
    fingerprint: true,
    touch: false,
    color: "Pure Silver",
    faceUnlock: true ,
    image: "./images/Acer-2.avif"
  },
  {
    name: "HP 15-fd0575TU (BG6E2PA)",
    price: 56990,
    ram: 12,
    battery: 7.4,
    brand: "HP",
    status: "Available",
    processor: "Intel",
    screen: 15.6,
    storage: 512,
    graphics: "Intel Iris",
    os: "Windows 11 Home Basic",
    rating: 4.2,
    fingerprint: true,
    touch: false,
    color: "Natural Silver",
    faceUnlock: false,
    image: "./images/HP-1.avif"
  },
  {
    name: "HP 255 G10 (B69V0PT) ",
    price:39246 ,
    ram: 8,
    battery: 6,
    brand: "HP",
    status: "Available",
    processor: "AMD Athlon",
    screen: 15.6,
    storage: 256,
    graphics: "AMD Radeon",
    os: "Windows 11 Home Basic",
    rating: 4.1,
    fingerprint: false,
    touch: false,
    color: "Ash Silver",
    faceUnlock:false,
    image: "./images/HP-2.avif"
  },
  {
    name: "Dell G5 15 SE (D560323HIN9S)",
    price:89990 ,
    ram: 16,
    battery: 10,
    brand: "Dell",
    status: "Out of Stock",
    processor: "Ryzen",
    screen: 15,
    storage: 512,
    graphics: "AMD Radeon",
    os: "Windows 10 Home Basic",
    rating: 5,
    fingerprint: true,
    touch:true,
    color: "Black",
    faceUnlock:true,
    image: "./images/Dell-1.avif"
  },
  {
    name: "Dell Inspiron 14 5410 (ICC-C782519WIN8)",
    price: 34995,
    ram: 16,
    battery:10,
    brand: "Dell",
    status: "Out of Stock",
    processor: "Intel",
    screen: 14,
    storage: 512,
    graphics: "Intel Iris",
    os: "Windows 11 Home Basic",
    rating: 4.2,
    fingerprint: false,
    touch: false,
    color: "Platinum Silver",
    faceUnlock: false,
    image: "./images/Dell-2.avif"
  },
  {
    name: "Lenovo LOQ 15IRX10 Ultrabook",
    price: 97520,
    ram:16,
    battery:10,
    brand: "Lenovo",
    status: "Upcoming",
    processor: "Intel",
    screen: 15.6,
    storage: 512,
    graphics: "NVIDIA ",
    os: "Windows 11",
    rating: 0,
    fingerprint: true,
    touch: true,
    color: "Grey",
    faceUnlock: true,
    image: "./images/Lenovo-1.avif"
  },
  {
    name: "Lenovo Yoga 9i 83LC001FIN Ultrabook",
    price: 199491,
    ram: 32,
    battery: 10,
    brand: "Lenovo",
    status: "Upcoming",
    processor: "Intel",
    screen: 14,
    storage: 1024,
    graphics: "Intel Arc",
    os: "Windows 11",
    rating: 0,
    fingerprint: true,
    touch: true,
    color: " Luna Grey",
    faceUnlock: true,
    image: "./images/Lenovo-2.avif"
  }
];